# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://xuzhao.vim
title: xuxiaozhao技术狂想
email: xuzhao1211@hotmail.com
author: xuzhao1211
description: > # "技术路上苦中作乐.
copyright: 'Copyright &copy; 2017 xuxiaozhao. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://github.com/xuzhao1211/xuzhao1211.github.io
  - title: github
    url: https://github.com/xuzhao1211/xuzhao1211.github.io
  - title: linkedin
    url: https://github.com/xuzhao1211/xuzhao1211.github.io